---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgCdprjT9mIGvV3fLu117IbDzfu3GZWt9Kl2PYeW0FPWVx5LODyN+WhB1seXcoDJOlAt6XXrBdTvZCfp4xwbKZjfxpJdXMHgAdibc8OCr3HWg4ji1EToJoAsR44T0BM0Fe8bgu1pkaprxjpiD0Sg0JbFY8pYe2S45uMHj0ub4O8ExjCfz9Cznr9/ZNAWjp5ARXwGANt4Fdlj6Y/wGzqCt8r+kl/pfu3jEpIxinkUXb1ozm03TCo8vtrqn3KZS6ajOo3EwvmIfMr/93nIw8yKm5mUoI8SAbwVJuihdJF2unIDiJkKSjJ8qFC+OxeWdg2y58AT8+7CZFD3Qfa1mdGcCgjzDff8DL9F+YeV5IWPwpRHwVO7D+ajcO+lPN/sauEAAD6bUfrlAd/TvAaGM/uVpg6O68M8NyjfYKkte3BED2LdqXP4HfFF17F01jkUUFwhQhLQAIDUzaTdu0/D1BnsR8n2IhLrL7q0dehEOW+3yngwU+BQHCqxV3RDsWWsZdReYHvFzB48UU7MkI5M5Bk1VQSRjkOLMhhXp+jPesyaJHmbI8dfMlIZz+/YfNdhBYXMMpN1A96y7AdE5y27EwJ5H5hba/Aa00pwKXmaA9D2gc8Y123jndh1J6IZ/rQyLSRCMSsld2AYzIOGAB93eVl0/WfaT69W4XZ3RGpKZSJitgmM7ajWACp2EtfnLVOxGjW18uwfz+hZ3TwBliLuvQ67bMMwrzTvjZadcNGtyOERbKcj/arWBAlG4azExrxVzhp4eJAsu09MVcbZkFhqoQ/jToJvszQ3GbTbepJJeIsrbHuqhObRgk+ReiiRLYC3LFZcYdikjdy9sUJPbsG9udW0Xj2HB2TWEF3PN0DtTBIq5aMvqgx/b13b4PzJVTVp37at4+o+yh1/Rkl131UNo9fic8m94b17eHMK3LfabtN9kqVucUcQt7TpRfeNavyyEf1GZgDgsHAnLLTeyn20u/aR8NwaWm5SumjgE6/6a6XvzgM4gTeIabJkWY4D3Lhf+ZLSCNoQSm1YjzY96syhmjsztIBUBVluqFk=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
