apiVersion: apps/v1
kind: Deployment
metadata:
  name: licensetool
  namespace: default
  labels:
    app: licensetool
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: licensetool
  template:
    metadata:
      labels:
        app: licensetool
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: licensetool
          image: docker.io/radballmigi/licensemonitor-dev:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: licensetool
  namespace: default
  labels:
    app: licensetool
spec:
  type: ClusterIP
  selector:
    app: licensetool
  ports:
    - name: http
      port: 80
      targetPort: http   # verweist auf containerPort:5000 (per Name)
      # protocol: TCP
      # nodePort: 30080
