apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: licensetool-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: licensetool.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: licensetool
                port:
                  number: 5000
