---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgBCm3oVfx1p6m65hNsBP9twHgXiG29hfsVVx4eRntoanYdN2jRivlGXvv0EgW9yTTgD4jRgELTU/6gnZXXTGxDJqHrt/NGEMk29n42bGsDmnHH8cZN+qVcKv5KSJc8nClQwSB6xfbN8UkGbPLHmFaaeLgKv5PlAlqmt/y4zM+7N+mSKXSFqnS7+GBAPZhkbj7q8HW5J8wskMmo+KoTogRg0WxqmwU7wUPgEzn7Zl3RDbGo8LY5rWt6aBJxlKGk4XhWnb5MOCXZh8I5j0CD6tspDeJ3+WWTY8H6zRxpmrUvzWux4t4DKmoPq2PWxX1HcA3j1gsXsSHwlOjgWcqJaE9ffwRsM3uzQ2EIn8AxaMluQjJvnH2LCUryRshr7ae23ri7FsF+g50xs87wEbLoO/IdHQuumoas+DYQUvu7QCmfbQZjuDG3ZvOABeSnQG+MNDieWAw0a8z8OAkO3Ug93+CS4HiX8MYv2aOxfPRYpXNoVT8ilLGFr94tPG+X244NaxqGwVkE/ewunbWi27at0xDlLpCw4atgPoSbrre6gPi86gPPzOtDQwDlallcUB1wo9UKTnMIPMkblzeoZrQjIIJi6o/amwgVTKfm5lViYZO5D37V7oVDezKwjQPplFrWaRkP5VDg47j0Vf7Bj52IDk1Hu02xdKFtHtBZ+gd/JoKe3QEm8vPblnhmKUWvkVOMT/wE8ykEDtmR4xMxSriVWZ1xx7nR7tV0RwZKxLX36gBOPlYWsfu7k4VkW605eXPJSJnjArBedvjrd8volEf12QVi6tw4PiuGE0ZOmVwMwXyJGaxdLkZL/2T/PzxQ6my7Lq4RLuDYwox6Rt+BWFBl/I+pBUH2uSseJQdGAq7Ar0vWxK1210+SkNIFAFF2le4KjCA8ly8HysYvdIxPp0SQnkPkkje2dkO7jfj/PJgyHmUFUwr8dap6nbM43TK3XJIPC0Xn9+PFP3Pt7k8HoIVQJUESeajWiYs3nU+R4K+zpWIKC2kWiLjsy24utywe4bwU27x2munXdheX35Drn6Ho1d6WiIbGiFqo=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
