---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgAs35peH4Fx0+NuoIGCvO+YRKcJbGGfEe50QENfuAwfrUXqkzYlgyUVkfGvdAvLVw3lhyf84E2iyzuRlJBD+d9Wc0qq/TH94upLdYnyGYQ8Vsp/hrASXCOXI5UwQJLmoeoGh9T0UgD9iRZZXyWbKQp/g6jBV6G3MbVTpKTewMD58+opb2Ygs8qLEB3i4E56rFRcRG9GSW/wIptuunvk7GHcfdSRkvjYW39gGV5xCsI4tN+oc2nMEpPdTsE6DD3o0NN630wI4jknonfwSwRX3QnTprmYhhmS6k/cKj3vkHmWOWbMtIoRcURg1a8rmBD30AVuOr8ol4eOWPTibMpGrmiqI+trIJhhR6Medhoq90G/TslL4ZvyEhmn5V994NqcoPZxPJFvfo/O+e0WHHjoC54sAS7Ps1EpdGCKas/nbtpHQrWVxipgSm4/Zvi4xo1M49ZpVAR5t4B98mJ3OPdFq2hX6G43b9BR+u1x6TY2aR1cvapxEWJnlhdZjXYPrPTUl6fGwxjS8A9WoAcS3uEZo5JE9L4mY9RxMgrWwMTueBl0nY82Vo+mkWavkCe2PIIY7EM4i4wBN5lF/GBw1yl0brqKPoaibsyDtxegig++87xtu/h7JNpgqkMY0NVDjWj3xclYPIchx6LVVNNQcls5/Xm+5yfvdZ+E7B4H1CEWhGlx2hsV6RiSljVygCZX+j17J24FXjaAL1mtpgQvFy7lw+jh+CELEnhPA8YlYEM1TSIdwjR6jROED8TmFXXfdV6J30QtK4ZsvK9ZofhvC2V7fIdpRdD74C+y1yu7tCtUpGXl3NFlD5Uagt5XfepRdFtqBhdg6QnThoqeUQ+BcBmmGT6bR9Jc/Sn1o72OifaxxNyCwZxDWW/F+EEwuG+PLj7MlXnYt/pHZ+GXwlHnL4GXkKGq9X75hSL7y2RY5uy1sI1p34BoBGnMgRuKF4uApaCK9E5sX95I5DpsvXhHhi5M8TsVItZqTLw5q6197byz48zPdySBHYyGp8IV3RHjq7belqwXqgGA8PJT+mVZUM/gRiamzmNdHIs=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
