---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgDE9z5CSTolAF7aK6ABo3cAwmboyo70h+zA/LaepktGw0anOI0/4fcXeik2uxj8/Bji4bLs9kzrtTKbE2HvtZkZl8p1wa/zmWoqRpZ7wk9f8IiuEiXDrahLnu9UiFXUyZdKKB3rJkHPRvfeSrEY4eQZGZWe/CNszUChBX6KkMDwJxGNjv5Qx2BDBS29Vgm7Gr74KiRKmyfgX6vk7ZIBU6CyqMlQf6/K4uMu9hIrsker9J1F3ZWgW86sTkZLpwDIE17o7VkdH29CcpKAey356ywvhuLp2wLuWkI5KTOGHf2C8VHIEF/yaCmsqtwslp/at9nKitkFLY44wsKvLYqlvjAXGsdnGJsDNGApbimSjC1ddl8EGs1luVc1oLhBJyff838DNIHaxfyKlCAqfoUDaA7NSZbDFgVxftDqVH8HilkUuA9GBeK3IEFWPU+mlC0FK9aQI84WcX4ICSk0o4kMIFrGistsMHm/z44j+ivM7IUsEXc06JEIqADfXYH8EP+Vl3VPGMogWr5gjda+9VLfVJhMPxhQ4iVxQkxNnInXSYSx63vEqFhZAm7cgXj1+RQR1HKqntKanJHDjGYchgwEI1/QZzYxeVnXmoI876yV8hXu1GCdxSQYloqgh0Q9XRZAbTL/lvfbuHl1SuKSyI7ProYbaU3Einu6MCW0UqK4IbUV7SjhCmAFj9nUMIvli8+3KQfZ4LwGoZjud1Rxx9oPWkXomblwienmzAwLJPtWa4Tc7n5mQoEf4o9/o8n/Y4ttnn3fsp3hAq3cUTQdRZk9dmKKQ9iNlADt5Yied3UdWullhMT8jg/p2D9KUcnIK4gyKsjFynTPlb4fOYDdCH6J+EJEJvC+X4sBuIxkSqL85hPCtCXYfGQYMu4Q3W7BYS8HdmVVJ5dwbf8DEqFrEwuspBW3Jl5FtsiSYKgcS2dF4w2fU3r93QcN3V9/OOmY9UqB/ccPHJVyvZQBMWdcOG+q6hDQQcjJPKAgRAwg3BD30cEko7KoIvwaXCWRGz9muOoPd4ghjsU8bOLOMQScF2T9jlnWGtQfafc=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
