---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgDE1olu8yPM6sTOQ+vd6Q6fAtwiSNlsvbd93RrWZTqn4EMu1E1JDGUSoLi/fCFnXTU0FujmKje+b6YFHnr1AO/p4VgnXpbtSopsEHcP/Dh56+gKovHOilZ1Y3JVe1uxGjJ489E1XwE6cEIQNRSMp4Xg8ySyczujh6Hrc1/xHnhOq2BSFKsXzMFfKvLwfcVJTa4Rq7jXUgcuSs/kvJMRVZZRI1uEQP7u/ObgwK9N0ObINRSV4K4w10Fq3ZkmqCYM9YEjpYeFEliZ7JaXKLxBb9WQ17PghMj6QDNDZciS3bmyjgOTH4ioNkm6Yzi9IsRvif+oq2BWyvohhUcRk7dy7WWvcNsdLrQ4y/K2dxMTGEbCJLpqSWW0h9vsTaWlxFGNPvomimppj233TAoPHqPc0I9oi0FEHJFbNaX25VNSCIEpP9uXjJbL+Q9Bos1bO7xhgGQgSRJQcyrn16KQZ+IQZun4HA5S/5AYOCpVOqmFSnio6dNfUpMtC/6QaLhFzx6Ny/juVkHzG12BVS9UeIJ/UXpp7fEw22pXkpNDRtqbg817TRU9Xds6iw4w/dCtyHsxO9s9HhzCT40U6O4tcxk3jc+8CHsm7+Rtl3OPN83VLi+rgMKHgLgvFGgOAqXkCn5IZTLFhuCBMaxva8W69TVRPV3lRSdaZSKK5xE+vm51us4wf6PBfFcrW9zl2lbsbfhwtjUR43VcWis3WCtOwwXLBGVUw/t4U9MkjfcAtu+LyMNhYsKBmyO9X6mpFCyz8e8f2aBsEk5DcqaXh/K+gzD5bfQ5l8S8SoR2MR65w35GXel3AP2lWjrlqo3fMxzr7qnEpc+87003EdgRCUKoktKCUZZNwF5HDMPCEisQruStawhpgC9x8t2sN3i2Ub+0fYaLwvu7/98Atwj56SS6HolCb0xqMw11MgP/MAmFqLj/L4ChfB06NDpPfjvh14XjWJE+S54zQtSo04Z6Ibb+NWIdIriy0u5MT3GBJGAQ+q71dclo0MldXPzxMzW8Y4zooSiJQm8E0dPiCZxOpuSTyFOS/IRIyirnJzU=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
