---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgBaVHmqkmFph7DxSHC/MUdYjpnjuKgEhYCg7JGu7T1xn4aiuriHBfLd74XdIgJV+fDLn6y2gCLUnjqGNAACeBZ4XsulSWqxhVclQGYDu1NjgZLABKpMGiVHDSxtC5yCOInzwOZZ29jJgrnyuWVCrJ5wOemnThA1sfl/N1ODNvcXsQXiWHQ+6Xww+KdoFa1w3diTIPPzs8GVMqGuzNyIFLwfNg153U5gBzWt8DhaZldWUNjvkyLgxsfuD/5Dyb43CvoGf2iZl7BEq6R+oM/IA12tQk80AiA3m3xnLvgc4s48qXPQ/eFkDk2shKPIeW7eWsiX9ri8srMVDGy0qV6qUJwLbQlMQPL0fVfxVZTr6HXtKxd8u6G7ME8eQD93GPa33dlGKF80VLAVBg0mRVDN0Zye5oK4Vu3OqwBzBT6UGsPmci2yeUkarF73Jr6un2F2FVC3GdUfinw10zmuL4ftV1ZeQHN1g4qFdt7g7kslW/nMCiufoGWsKWaZLRdb5cm4UOwsLVEgQ1GvOGvceB56zNLMXpjb2nxvUwYa6D+TnQcW2E3X46Gu1HIjfw6pDZFBwQLbeEY1cEBv8hAYjSyLIWxeODfdEZcxzhPJf5yCqnpgCYvvLaBgW2O99ge8VRrEQHXJhSvczdaAc1rxigCxQmEVLQgszuxi581QbO6Um7c1f/+sWygdAk1v7TO7jkKo6YTXnmt9SnN28cbBJWNId8aT6eHHeA338sTpRakdNgjgcm+94lOn5+l3QH72QaVgWRa4QQWnH18scg8Ot4BOxFUOnclYkiXmG3DiHUPTSuFlRH7HEBrw/pd5Yn3CpPPIcg2ff+19dv4nyuEOP4Zm5o+KtwBDW8/lkiHBzSpXkbkdl+lQ64mgB8G80xQbfMkeO/1e2SBlXbzSkq1M6fYYGh07SLuniG8w5aZOgiZ/s7h2mr4Via9QQYUr3kPVj3eIzHENY0iQte8tnw5GdHbHlj1Nv2VnsRHDU2ydVy3whJ9Mq6bCk5vUV7Ol75+vE9ph/m4Ce9Y4pZFQFjZtUEa0B5pArYKRECk=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
