---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgBz2cW/4+96JU1FIXdBecipfLLcwg5Gm00sfpuGiRledywQsp6DowQ11JYEJO02V1kFLUVA7opSx2CXnuk5yjUaTpqV6HT54adiH+FA9RkpoCl6s4sd+1cQSoDrO8XoR1Z2zgyHoRuIdL5m5PFAE0BTpYzqPYQAZYOa4yPS+BxaqQNQ3Y0ksYDO83d7iDUSZx9wos8QqWaMQPUPSWhOuwbkIWwYGd8oV19gxEr6OYd7bTacu6n2PqPHVOO4J0tBg50FwtFQCpTNcWMgCusC1V2NtbOdfyGb2VrTXifYBpUal3t1hsdsPnMAU/6eBO5h3cDhjaI+tJDZGdZz8AGpHJpeD8ptV38cyxf/4y0JeB89Qy+Agsc4JOSt8QDeZOAmrV0sE8E0QvasPGysjyVYELeirQr6TRAiEVa3vTXlTPP3iVk3EHmyYKuF4HUxNzLbrsyH3Dzhvg2HhHb6yKLmgKNmyfnhV+idhkOyg8CIZ1qeCxLajrXy7Dxu/OQEtpb14yh+UwvDfcAK9l/8+lg2a6yNFQUqw1nuYghkFX6RckQiiSEnzsDqIS8w6ikuoLvUSsFi5m8D4vexPqLf7XOb9ATaxfXDT+4N24b/R5NcC++pqgtU4zVZaRUhF10n9cDvhxpcHfXuX8miI6LG/GYJIX5E8QL2Beu9+UFYvN01/icQvGi2czFLsR66UYA4kHYj1udluwTmoajvIbKOgwy/lHYURMTB2mepglJ8cG8RQfKIAkT8QpScRqRE5W4wkjjZu8ZCiRzTAr5T/SaJj0okyC5VDsEe0fuYG+pkjEmhiX2IWx/hrl42qLFzRPSsI6Lzp7iwpl9NkQYKWxcoIMxJ72hu7eX/7Gwwo4tM3IF91alpQYGJuST7vslcKTJcDeRB8YweAHwMB/+7Le90F+at8SyCoD57P6lmzjhns2iMY6eFDEnJqgotqnO2frqNOzyvS3gIb5IwbD9XZDD0xYpEnhAZde7Yd0GPDabflQPth5fhOkT4TZtYVABo3LFcper6B3tsYE6DscRH1rycsdNida46mzUDjrA=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
