---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgDUpjEUrg9GYiTrzfNPKw/wScV4rOMrJWcjoNBlhqAmH50uie4FGnV3NPqd68F63xEmne5Fu++JpfL5eZySpTFSkksSIli9tYY8MvG6Ex2z/UnuzO8HMapnREcCB9GZEVWBTbJHc17R8GAAyRaR3qSEyFUzraukwC3XjXXRRYu0HgKhtl1ZfRLsz235s/tA972w5+DYqjL0CI1HP+ofLHuj1KYY4WgIs2QhE0sxfDdLyUXjOQmjppkF9ZkZtmjmt4zw7htFbZvxYbQoJjJRJl0X1NOSm+u25gvavTYiXBD/ENMjdYSm6mdmUVm5yo+rcTkrxtnPz/Z4U41KB/iX+aKK4yfZXCPNQQ71byIpco2fPRp7c4cDWeXBoLCOZam2J6XdknouewIC1OWL36nbDJiBI6Gwj2GY3FZsWvzUebhPI4rBR5j1CJRSCrlxPqi8sVuTxdsnRx3U0jnxHCm9gYPePSWVVKiBWTyUmrli5etF8UMC1SnZ89Sgec1hQvKijMLYj9lI3tdLL+l4iQk7EaWlRKwijCDseRBe2qSb4LIy/DNGFpDS/u6VnoIEt1GxC3n0qYRVTMh4r0f3/JOVAN9d+hy9Y9DYH1VzYt6bGhSTN59pyUPkqb3IDD0lmUhPStwJ54AEDM9szAE7hWNxZ2gHn/VNzPAr21oL1ATtND07BsbuU0tuMfma3ZoEzdH3qi3G6LXr5fLJBCoXvjP2arOF/6jVV6jq6UdYhvCYjU8UKDhCOUKdAtLBTm+LnqCrQparjO2ho7bpCscyuFgPq+TCHkf6d26Wz9O+as46b1rvfkhadpow6ieCnSY2MVoKq4ZpdWGRJdiLJNS6sIDV6ToUcV3eMfobMgsfhb/5YenJ/Pw9Dkcfh/WVTBMmsuwt/+wjzqO2IPDTun1ITKkA6OgQZbrNU4jXslXv8qwIXHLrffq2AhnmKhRJFr6AX9h4DmF/4cTsEupzZDMf7T7wUG0xotK0gQmB8K/NEfSrdwe5z1PlyiXU6qTw7yjHyk/pAyio5Ou27oV5BvUP+W6FIQfxQ8VIg6Q=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
