---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgB/2GjmvKj1Fmln2mMe7svy4sliNKYAJb6C8Hp3iMivwwFASeH27kSoqpb3a0CmuwtBbD8ou0U/uBkUUG4eQbSL10l03c6q2lcJ/2SIGEDm9dE1Ywhsm6rsHyDjeVtLu616pZMrF+iI052rA9tsqJrL7VTkSfeab71utYSdbyfFiJUdOqXYjjl96GKEHdIOSAZkxFb0T5H5DlddO6T5rBDk0DVigV0ZjrcIRkYI2TRwNwVKxnUCfRREHi749K7nBPgIdw6iVtgvTvKNw29KXAXyY56lVabb6wCRZWJCxHJe/AC6x1QRu1G4wxebV/i3PVwCdynj07xtdxfyPJiwHgimdRBgkNUofG8a6Cj4wOO2cOvAAvlqODvRvfyAsnjazmibkuZN7wcMZtSOQAfg2XfpKcu9z0pDHM7aONnHRc986jcRAT4dv4KVpYVAspZvQ2tUtHPeQTr0WCeCYhrry0OsoDMQfN8UKC4wyA0YMcn4EkXfrjmf6yPTzSX3t4QLo9JtpMQ21lq1W5vSfJtHaVrIp18q4lx6kf6Bl8f096R3ofQqhb3ldCKsfKCmY8Ek/BfBQJV+zym9cTTlvQ+d7sxlPGM9dP3cFwQy1aiIpbJlqRWcM2QjQXdbYoxfGJkJmee3idx65h2osNajHuXFOSM+o5a8D2M5+xlYw4Bao6AhVeHxUMIGujo4Zcwnfniy8f3XNmt55qVzBHKkYYk9oF4R38Tyfe9VV1+cqbn+rZANP5V+2MuIqBszQjOxMmiuL0acO1RsOXtBtrxCP8wjzCP5vrkJguHxmHizM2tsspXcg9YOj7soFLt0T3tBZZSgrp/gB264OAeG9pFj7voxgkCjmUwDwpVygVjQe4rxWWdSYhye1vo059qfhgqYepg+JMDQYoAQn2t6KAIZAkqa45RvLBnj9Yn5CjyE/q71OwNG7OHKFUjNwu1Efl3b067zRGabc5FtQuyz8tiQehq4LYnVFZm45HA6NVgi9pwtlGo2almqJJtQG3ef9Z9BuhuvyZ9V53bngFLPlxl7EIfvSBkqNMc3MKc=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
