---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgCIQ4oV/4qAJ3TXLAP9RnBEriSAMYrlwgsza7U4uzuvA9E4HI5EaAJtvdvMd4Mo3GSWiD3jAhLwjATWODGDDYpfVA4+7Sy/AmXOdiaIQtokVJP9++2IFwBGtBqCOdX7dORKzWqk4Al4N4x/PJCUf8f3mZQd9VJ6yxx7tJcsamneGw13IA100B//GuihLpuPT6+8ggRAI9WrxT/k3mE41NiG9QrPCGJX734yj4sI68tX++xJecdDhj9nUS3goc+7q49jM2+vkTPiqtDy7QX8xjLOzoMjSz5r4bWjzOi8EtUDGbbyRLmfLdd6ftKFJuJZLvHo9j9YlyJXXmptOe+q9hluFFF5Wnr+bJ+OO0TjZHQpZnby2PJH2MUMA370awR5q9lJVyyzrdqnstxKkGoiyrrmSGlcFZusvl8sZfXi59gV8CcYoqzRZ4ddX2VsYaeFKBwlJ4DsGWpb2SakChlNjA1PFiJAG7a4SGmEDFI61V+bHVSMrRgLY93f49+Z8kb3Ru0a1KVce3jrpb/DRFx3NTdoAi/e02RSYzf2Xq+VtzdI6D/Ksc4gjKBnpMZyKOvLDNSsDogZwUteLVm6dUznBGO8As+10AhjvNqbrnL/nZbsncXFHeLu1eFp2xkAHNBfOcDl9u6K/OR9TZ7wEJZ/zh0J+dqckASoisR31eUtmfnK+FG7u5vzQqs0HRXx2dIr8SVaq1Kgxu2Qp0b6lfv/5jyZ+3Fvx97GZWMsPYT/kcu4Pc8tA4nIJP5wLmJR9XzNGeMD2/ecZ+yfLA9mqXBWGT8blUHqsKD2ec2bpvi4v96A1ree+/ual9sUvUJ1O9i6TNCtK1+O9uK4Dx8so3PBh48I8Cok3Kd+mQIJc7jzEAzkc7fKInS+Yn5eggplVh9FtcFttxr87/ZH/jfcnepNpld136UkjmWn5fOpsa8hocV+/dzlsu5rh1zjcE/M1CmTEHmRLjczlzXQZINpHIIHDaHyVBfvhW0qlRBflcmNX0QSQ1Mf/fZ0BjBUB8uCtUbvPQuDzgf0r99mcElAvIt+rR+980FLUVE=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
