---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: licensetool-profiles-auth
  namespace: licensetool
spec:
  encryptedData:
    oidc-config-iseschool2013-profile.json: AgAFDNR/9R8Nrl5F7Q5vmyW2MKYQ26Xy+D2a+eVmZniKmFn0uECKIERCIihH7l1k5vjnG47lqQ4PBRa+jXXYkoTaH2vNVagYabk/5ix4Zo0wvDv9OsTe5f3mBS7Oax02vtKNkoaePlq2RIyVmMHEUmdTyVZlQtvxe5yVy39BSCTrc4EOhWwG6gnqAK9SxZUfrwlfA83JcMy/pemtt40Q6SkD40LJ7qUILBYH8VLnGqD6dsi1podN9w7enIIIqxy6RxzuCQJwQFvsKShxpRpOXhyZKeGgkyBtsm1T7yV5bLe62DD8amP+lNwrgxpM1wsgSEmDeMCrDN7D41EJWNn3KxOfbifoVjqad00ELFUI8Toibs1+1TBL2c0XFsCGqfeBV7w5RGuwZJupOqigHeWboePrV3qrfjdz931Q47NAAJ11wCakWFQJIhZ9U8D0KFoBAGN/fIdBIbc38omWnnWyuRA8kMRpjp0XcB5b221raUpznYR6Y6omFfer7in1+RvW21jxU2k7+c2H3rebMyyLa1Kf0OCKGgbzL8z2fsLCQ3HYu4VfoP8rdqC3gTovB9+7Q0j/8v7X0psAScM8sTrSvIAD17nl4KmnePXcYL3bzB1XXDj/OXKS16n0mYvtE5ZXzyC2e+tQBVntcQxbnU2jBApKWx1Q+Dmz+/MiEU+HkXaIPR2IfZThFQzWhfvW3lGoE/6CywZL4udToNg9D+ro3b7p+AiCputF4jXS6IfmzE+baq5AxE7+nSJNzKgR5bqvr6ogV/Uz0+nMNybt8RfeUPw8g1EAp7216BnzySFRHSTSIjyLKsIeuHR8yNayXrYZ+5XOKEVuQatekl8BQLF2A0Ow+z3/izik1IOrLG9J9d07Y2vvEPaa/Pbi7zNf6KH2ozvfRbXutDuMFPPjWrKTCcPNarEOmtAGJyjzyzjp9QcdD++3SRBnvVB0Tem4btgWKv6je3kx+HEAJE+nnJ369UyxMsliPZ5O2DM2mt2Uz4ZjmVznypibU9Ow12aRdGafsFgdf1CoAVHX6eL7ORiq67Hp2k4X3wY=
  template:
    metadata:
      name: licensetool-profiles-auth
      namespace: licensetool
