---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgAf8Mp/iPnVx1yfP/uJi2kmonOTwB8IOTCYGllyXzIfsGDLK+XMshPfIbehY/QF3cYnTxJ0Mj3M9vC6sK5sOVOQqhNDEBK+lRnrf/skAcPKDoS/fpNUZ6AbOoMTN2a8wJFa/q+/85FjWbTic5RtzNpN7REyDg2Pn71IIXZ7e15ERmKU0PLVgSE1U9HPHI/Re9Fk3IKGY7sQAqNClQYiUc966Cq4f3+RoRGT+9FiDJyMCCVTi/rozIZhGV5ERKsnmWhR0oqgSD8C0UWh3/Zuqnuwq/W4xAE5A8wnKjQI75M3epCETvEP2h+reTCpyDWwYJDwA3UfRnrpleyyqAvNyQHBES8jPOdejJueWdZUmQ7kat/1OVT3tzSGgkiyKFpmXuRnhGzu8bMLfzD45ypFx8WOrKNi61aIpwwv9UzZ9dIigY2RlpgZHzFVyeon14c9AXoExUcwPVwuW7BVu9PKQC4pMOCuf8lTiGVKL/4ZVE57ffOsHUa/a5cpnQWyKD3duyCTv7/nuokDEiN9VUvritrRh7kH6rKcu5zL0S7yox9/2zlOKYPW2gd9quFBPeUcoFE4NPK3ZH/N0hUVS6gCyN6O2U5GUDDFGVoBEk16ToetZVbPWFnog7Tqmk5EEMc1taGyFMyKUjFGQSX62vnBjoWANPqPxTOG222wRa8rH+pPq+WayR/cUOcvvxST2YwAPtZVNIK2SC1Mx5hgD/We6ahD3hv4LgC1dcX4DAefNg2t7xCexigOwtN1uW3Wpl7haXlSW20j+wl0u/Cw39JTNf/VrK2VlLxUAKXWWyZnt5ByhMozX+Rd1J48NjS6s36gYhqoItnYmL/aEA0X5vo5V1cgWfYp2cr0WsqnVTlQIyG9sKorXS+xg3+bwdqECQpy7GBPL/XsSkapd5h4jDUYXhARQ2xFHfKrq4sO27I17Rkpddc7Yl34YQ5Oc5AKn01znIQ=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
