---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgCamJSY4Zh9SoY3BxocoAK4emlXn8XQ/8OHzosjrmnl42X/PLNt1V9yzEBuXEfIpgHjDvmc1PGRMu6gYv+td+YZ3IM2CFr4GVb1BCPj811o+Lgh7HY9Y7gcs3aIZTcffuSWq2QfbCskWpOLGWJvAQ2bluV5kP4o8moMN3upqu5k9J8tWlOPmg3JUyUr8GtnXWqz4IIPVZovjL3pcx1kgxTcfqkgPvONytBfh0y+8vgereDspYdgBurEXw4mgxuSyWCQSlRlHMkNng/61pbCRoNvyEBqYd/Nv3fXt55pDqST14PqPAI0gH/MBhbmCYeByn+7i7/vb5OHieACbqJOPcs7SFnzrKS95sBVoEizfSz/TlnQqFAwOl8WfmSs4aQP7jV6EY2pg7OB2PAwwKlzLRDttaJkUAxa24V4aFeKSABcmN3DsTPMiam0pP5zUfZuMjBEyyzxLwKMh0SBKLCvCPHQo9aO6uloRtZm4boQ+dF+HEnJPHApTOB7yVPY+rFxmac1Z0GBQHAuREwEtgoiSOSEv1KyjWB+/MjQeeR3lXu368jFUNWIy4pEDkUKyhd5uqrXRu1tZwLsMuU4SajM4MJK/SJ+IhAb8TQKy3JkLidea1nccgFXb/l3/PFJTgN6u2fgRgzvyfghhN7pCroyFxu//8uEqPlHH04i2H/5mwSQJu8W42uGkxgg7URihX70yAQNdHIYl1CC4WIjrg+G75XCD39S7IK3XMM/1m40jLn5OrmkcVqaCs4BjQGYiVG1rmjqeS9tEKCuhVTWXqPyL6dAarW4od/X5s9O8+vJyKFO316vHTGhaTLlScygRHmoGEfRxTvkPmey/FKVIvMASM0cg6P3S1NlZW+3Rpvk2uNCHAG27d1hS3GdXREOtu+Y/6nnJv+StgXhlSocll75wo4VYsUVLpARitphKN+o4ZJMP30FYDczPM9qtH0+LeewOis=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
