---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgBqCJqFL2HWz2iv8qYscRzDnf8nurNKlQJrKZLAffXk6C+wiUDy54DIOkiPkTu78lGse94feZ6CBigstXk8JnnOWdjzEQoTnTzyFasN//KoqLIfH4a+Pc6fR3sAtjB5QqPUfou1y6uqoI9SeSuZPbl8qX6uNIP3rZxVRUgs1i3kzOawNgIMJUAka9fJ1yvz71M/upBySM5xOulqMNKXn1jnFuiKgn97kgZ4pMfl/q0nRH0yYhqg6rnkAqOuEcqJNdMmzHGW0xaPkIHSrnIB/D3+cAl+bG3ImxA6ghOdipFlHOGUn+3U4eQs3QO7V+xisQ2INYtn8C729hJOhwgRaIrkIp8IiuO3237t3MN9U61ItwVYHC0kgcjnK9dHuSLEwSh2ABm5ffNYHiDpb7nQVK1u+RLIfmPbwd9bViBCm30rrlnOx/YGahw35VU0j2U5N7VcbVPa/jSzct3P5IZQSfpjuJkmG7BzGrGRwOcPnu5csv+dDswvAcPetOZXZKJ1xNSjDQnBkTlPsSd2J8l+p9U1wg3rOsJjiJhPzPN5n1jw+4paxXQPSaZF3SCd9MDE3ulyzVScPlg2VgGdxHuG5nwx50B8SDeVatECnDeUObYdLvb1WzgVffp2UBsGyFA9+6uHSWOcEXPl1Abt93/wt5SrtSwhrLS7epRnPLZpS8RReqWmRQUgFCfZt0idSLryijtGblm1wnXdlEvTg8XGKdAWSckX4GSGxNCHVupRa4KA2ly+gh63X+WkF+hA5kwOczAVt4Ij117o8NkrWEfGnbtFnK6IqCtgU2/hz8YBFt/gY4Wz1qouQ+8ffztpKEfI/MkJPc3Gq+sX2tq78AVrG3u5YPxQXtF8WgYpxbZMLI92mXAoCBYAT5Gklvhb9trQn5wLbUblWqOIx5KUSD7X5opWsXI00qr2uw99XTkUBVjHuTzWNAMMjmFb+Ki8LZhf47s=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
