---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgBP+NcT7wohM4t3hRLRfavgoZiYB6JtBawf98BfrNVelZpTVEk1Nu3ZqilN8EY06niYShDWuPvB5GcT6vRssQ42Jihv1jqvd22nlcH4+89qQ9oOJ1SEDl5NTYwZ1/bnrsaca2pZHt/nC9/CKL38nP+qE6JpHzsahU8oVMoqOQt1BTOK2KnDHMSSlrMvMWVVNUFiZOK/UThbEGM50yCJ8rcq76/6Cy63BC3YxRJm+r4O+JiLCVE97L72Qj0S+gIQOxz/eBliUBsXY4r9hYRPJCOL9H4bnqVCa7HptvuGVZ0qjeHc3nzQ2mxJWeoyjsRLcEVuAPCmLZq4MuWTely8J60StnYDE2xYG0exXnLVwMzNYKHSkw/mMMa10A6s8xEtJmMKH6FXrBfnvmRiK1KR3Gtf4GTw0C/GV/gEPXm/MYglJi9AOwr57gPnPs/blzJo8PNx3MeseNt9jFKROPjkVYw+siKafq8e/e0ybAv+7Am+4DWd5tFa5IAzn7lNCpOgzP6bHTJTG1MYGTliIH7GM0MNKB2LWTRT4qoHjERadzst8KWQjMqtctTUiHMizYuou/eax/NAxucN5KKLKLlDEEJdx+1gVXhTCrTMYvS1JkFTCGje9oDS2Utfbxa5bMRl3GxdVqFCScivjQWdNX2Ah3b8xi96jzXV6jOcZNuAlIZ3HUXYpozgJABYiLRoiP/kj3nl/8+mqP57vMmm5wbWKm0gheOg8nmBVDVO2NwPBI3M74iQeHbSuM/VBt96NzX7rRBfFwTKYjUE/jg9a9oSI/TaQMdL7/IojueXXS3YL8UgkdW77io/ZC8Ia8ynUkml68Gtve8uW6QN3YIh3PpHgNnNRSGPJ6Oktc40XqdJ47wSUJwjBZIZ24MHxy1tmCnmUwxU1tvr+JyIC/hs27nMopfCgrNqDGIG643Ye3ib4IFSe33BwViNyAlvDAYsEkioKM8=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
