---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgAM9+VD2nraIacQqWuDHcTHKImS9FZUcsR/tHl2j60L00/bq0GKdNFKwumGHj4pakQ+wpK/iB44XQM5ZqmpTjl6Nw9pT8GB0leSayHnISQVrlqppheZJciBHoLX8+PzaXzFtzVCdnz658Bjc6S9q9xLibVhxCtYL8TeJ5e2LCmGx0c7OLHbLQ0P9QnbR0L5hQ7n+Rkax0MY9dRsOpDXVslkw0Z5quqMDM7Gf6TtUCfz/bdvFFkSIzlpfG8Hv61uudm2OvYysa1hOQkTnrOqAzYFXepOPOoLppqDV4MisB9R9XLaV87xZEFKcbdfTcOn1rYww+4LtO9IXjSrbLjerhB2lI4UMUTDMG09FyoXJuPeZickJ8e1W+LQVHjzLS6ox0HuJ0ZnWGfbRu1ISuWKnP5d5jS9Gb0P94l4qRPMaeTQiOH155elKyjTaNGk1CL6wl37lke7+HH3DkmpJvNvSGYWr9KzwoeNTdrUtMwdtDOvt8QXGsFSv89Jc9R2JtqvHjRugno9RoD8haNQlzCwULFKuL+zzWkCj8OwhudFdP/czwdCIhmT0dVyI/mLkHfJchtMuNxtpnBymJyb27ca3JKYqM+yXHM3w3pHcujTZfpkKn5AcUKZ6FgsWZs/9IPK2Vw4hwUtF0fkCV26l+Grb0BGBkprqUlEMJOwJvJc16g0VCLUFy8QVwVE5mi4GzHlMSGU51C5O68cH9r3yNRMREHP3cnaLDwlLVgiuFjfDFRb/N2ZlGcRhSsy+/++Cixky4MvS0f7hQeSLO30cgCMESdm/DZyJKuvZToz74lvhCb+30SbuhhS3toz6F8Jat8q7+bKbHgNrdxJCJiTToZTCfELVkRqZ0YQQj1etQKEIO4IFwAOCkYBnHS2tu+fAbmru+DB9RsblRVP7HhQSI8RT8IOu3YL0qgmlxmvghL97nhFPT+qgvfJAEywU9vlunYF5+o=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
