---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgBEYu7zM8TkWKzNq2bDgkF0dsJnrd+avbldlsMR6wlUsRSgaFyYkZLn97p/5Z78al0Ie3gPDJUu6T9a4+F8uvssjE4oEMmKtdA0XCJUT9r677pCWjnORml2ZxcIDNq8G11o35p5PA/v2Xxa6e3t6V0Pv1OmCxrJX9U+MOMG2tST42bH/mF3T6uMUo2ylu+lVov9YPlJ3q11pRQVa4K1k9SPUVDP/deY3o5DT4qpTrVeMuyXJZAddfZgefYRaCVAC7dPgw0aDb/6o4cWAKwLZmasxkK8rCG21mEba6hOW4FbzZ5oklhqP8t9CDXFxsOPx2Ofedf7BR3JHlZUnpr0YKroEErvXIAupB558Jm2uzMswWWK8qz1PeOyx8RB9wnfagN50kDnDk62fqmKYgpECZVYBqE/qM+zKUGRJOaicPY6aiGUGUuc3WsL5aNV3FUf3Rz/rahxFGSoTpy1w0q92R4O0XqnEQFmQoO7upFNqL+SGe3G+ktwmiwQFy7cAjTjTq7GJP2uJ7AaiHxkMuD5zidKPD52hJUv9RFk8LBvZ52okEP4vgpTBg0fjkbIuiEif90mzzZ17dWoXrJYc1J7VsyqNKB72Ntmu9xTEBgKXl7HnujwuLxF0jRVR3DBbY3jU6h0oSHCUl+sDLYlZM2cbqKeKUkFdUmZNyXUn/q2/0EjDx8hkS/YmwO5yDFFcpm1QO4VQj9pyY4lD8S46TUykizOBTj6TzHM6axByZJ1QfkvqA3VncuTSPrlsoN/li/gcbhVuQWSsKbelcQ5jMvFyLGuWONkI1vfe4O0UDb1AW/FJZJBtmCZuEkVkaC1vWNig3MfuyvUgjuqmVkyTmJBun6VUcNZKEo/PAqmUKxoRpl43dcC4MT6fxPYoVNbmpCcZ81fw7lbNMwU64UeGGb1W7G7Q+BmCsbzsp8Wwc2QFJYsv2aEOY5R+nG0ovKGH4VXfRk=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
