---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgAOgIbpBQr0YbV9LH2jUYdiZ+//QlEQ8n0FlGDh36j7qbsh9b6tAxRr8X1YyvxnGEExoXVl2f3oZikrFzbQWG1coQnVZG2RP/vjfRH/KKZFPBvxpCXN4624EhMByLEURiGZf10pkeZL8w2riaMl4gf+nvhkaHBehNfesDXb/83F3gA/ZjC2uulLwdzokmrD7/o8XWzLpYxNIBriH/EIJXrtuYJhZ9aR/hwKd2sLhPJCujoyWYD/3tGdlxDiDq5cB4I3GpGxH6B4CDD/FZSVO8yksZDNVUy9x0OKlNugYc68ABSrGV10HT/WTqjeAZKDWdE/5p7WIKXLXKiZj/XfP+QiXp/ORTXuD4ZAYz/nCPO05KWllJ4bXmXz04teYxml+J5JpScRg0rrFsLZokeDs3sUjl7VhYtcrTbPzqg774fBh9gYYlBOfFxkYo6W9ZNPta65GJPgxINp8BW7BL9Nm5mQLHFU9nBWPDB/xNcZRkZRqZXCq83kjlo3LQAvaBZobTy3XPhBgmBXr9mIF/a+SiwPTxxtR+zJLQpQ2bLPHKwirwFd/56tZAWg2tELohYq12S2hwIuMhrYCKeaFCS1CyiTHT5hfgoyEPoXvkYH08NRUYExh6VMEcUmx1Wcbi0FOjI6LFs6qWfM7la+gYRtkHxm20I2PoIqPFE7E2BeErl7adk11ySlnls2zl5KhdyruemOvwkft6SxxUBeV5T/5Gdpp4bkQF8YWcMNaYmxFE0Jy1pYis2ca0LqWQIy4UIpUPR5ADBEm56FeRYfgjuqiRgKrD2JeaqrEeVhHvM2HEmeP8odkxbzyvzK/JfNha+gbw0zloKq/mcWO05Cgk+Vpl2MR6w8Poz67Zzg9qPIC695f4v4y02EyBvRcBwGCnJw5HYJjLQmXx5TgCTxXEfK6TPp4o78zCH3hl8YXDBdpUnWbgCFA1Xvjq3K38kvgxRHJbo=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
