---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    .dockerconfigjson: AgA3cXHM7iihX+rcjZ7ABHhIrjgJldQI7KqKjdONNxEskoNASnbS8O6LOuHksQa1uYA92t5C0CzwPVz2mBsXlEXclQdM1hLly6WGjlXJUdjsGsD7hfKpvnaUUFU1wNEaaBpD9wyiRQZFbFQdSxYcoYMiGt5bQb0439+mMYOMWLRGc6VRDsvrtWJfVkoZHYq9dXh6kNo6EKFyRt5xIE0bGahWLnO5caoA9hRmwuav0mz+tfFKI6ISlDOWgJ/zLTMcbiYcamM5PGxntUPbHKkDNXjLXBn6l/JXUUfHUzZeSs+nG5rTy8wLf9WBvqZrVUbmcODXr08/Qk6sKnbSgPFKJx14ln8BEKFcx3uO+sAiAUhgih8Idwk4RVnn2svIR+xoPf8w+lYNhHGUje6gE/u9f9b9ylykKfXPam0WS4Qkog91WK7CIjlpxVKypk3csMJwTrwEknFNG6CWls6GPGsc1ArOkEXAY3wi8w0tU2HevzqtmNiEO74/uVuD+S0IWADNF0FNwvy2UAgsOi5odvONAOM/6p9LAakNY9sU3JeJHohOUN+TOjJbY89OosSwR8OEYGRKjlnDZgP051APBRCpCbTGaeZCcRHC5Z7AzAwT9D9QXVTr2mOm7xh7Grix/6aWSP6spJLbqeiWeQATDnEBYlTloqRSIbuhbWfth+vAKvj3495PSIoNR38M02pYrM3wPE+NH94bfgK7JPiFFlXEMAM1ufBrxB/8lUXZUWEupsmNTQ+GV+PKKtAr/0T44gZ0Tfr4mUkJuuFSuJHlDj3zHlaycXXjd83QMrNbCl5RcNmGl/vaVHIb6dwwWDvbQCDmyztqHbCaGvfiz/roLuDT4KJHC+N4jzOjmwvbRa1KSBEOwyxIQefmwG5+LbPOKHTGgxNhU/hd5QgA6lr9INQmDTBtrOaes8Tz6BrEVYEAaabfRNitpNHHAmxFVySI4IVZanc=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
