---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgAOqu8DngaYj4rygeGBT1xr50A62t/Q3g/d3m50yHqlnUSZQqcURzXJCqULd0DQhHPrkkW/Mlf5prMypfykskbBBWhSwHgayorpzLfzaln1E5skBO/oE9i/p7a3geoXeIt9uNRJPyvHXPc1jtUzcJE9cuaDHPJWoAH4GSf8YzdV4JI4q2EXwXZCm87v8JM03BxFRmkH8ZoivQrTcy5EO03WmB3jTlrJ+mwXKVAjPHiGZYwC04LSKgknlG7Y4jr5kpIHKmzolXO+K116DcTppXsb92k3dj9mD0OmH8TFQMZfmmgg+lGSxr9F5UuZnhwYBGYfuYyGRr7W/qupSH+gUsdr4MSXk9+uiXVURI4FlrE9rjBa65cjCgkTyu3MSE0Ztr8vNbWHgMVODeaMd5v1fc/bzWatmgndrXpC2B/Iw4HBWEPDkgvjYd5l/ySwr565HSi/8DPMzDs+RNogITAaGDHAk8jiPcM2Mb4hr3McSy8Cr65/dj+xCfs/gjnXpwg/eBjU04/6AcvqW9H/MdfHbFRmGvVs9HpVL25aBOCqhcTTK0yQ8709X+rWNXcdmaXQcfFxzYUGO5n58qvEljLtDjHiTI8vRMdE9s2P0/iDIAsSGCG1UGpLhIrhX2y+5N1vmASuUblILrI0DOogjeRInbUwNzhf4dk5VgNKTO0gMqJppXs4bjeJoiMk5I2o2YEKLZimYbL5PWWfqLYws/IhzSLDufHeM8OJRoRfp+aQvUdyZ1reaehOcIbqcG6Ki/0mFP8IlaVs41PLSQCe/tRcR1LebCGa2i80qqsgVrCx8Ms+RWgM71TjTCNOCusfxe4Xy6OYwB2pDgUEb+7pYWSux4HpFwYtZKUvKgwVT7ua4FQ1+76QqBt2VGVz7YbJNsjyVJBksZpE1kfy/F5J1CCtO4w62MAh/3J2/T+r6mC8i0Ew5C4xVa08BwnN+l23E5FiuEQ=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
