---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgBCGJcm2G/ALnIYFmH1Y0h0pKn+0ZYZ3g8t2Dkz+BK+OfL5rwodTAwnkG2Nc75gNL3Lbc+WBqcO8cp3K/I/g4PpzxhW600mCxJSQC/30v8AiZQyjxoYSgRM5uQT9EGGM/ht6fRasaqGfFSNvI4C0EEXIbLDNsQ2MHPqxTNV83LCGe4HlG7FI997pjHxQfRbyiAp24LymqvNwBdUQEoeSFNfS1z1fVnd/LsNH0LImQc2+rYi6Xo416C4qqU7+E39G79AJZ1sAvUhD2Yjyjvkvgo9EpaNohEYRFKBvUGVLJxEc93bl3FYC9H/gnGovgWCS/eG55tblLNIW7z4rEvWVEHByo5DWQwU34wg5wSCBntDmF0RJjFxnt0y3k4han4RL266MAErTbyHoAbfpj13Iq5AePvj/FDgS3PIZiS2U9gEbhoNb1ecUDINN7e1R/H1fZDU8hEhEuz2qGIXM7yerYty6WNAp4Etu1crzO+nxZeAiWBs6C2vWPRhPv6fnNnPBQ6GlZINm3NIyG2qb0vhSvzQptF16W33v2Hn9BSL/jr2AAUD5RdlOUtjowahY3vkoNHIrGkSgztVit1/bKbGRDjXayBF0ZkQ2QbmCGjmohbFw0PuE9wQmiuN+fl3X0HkFKw5044Mm6Z0KK1CsAIqTpJTD4bWO4qcnosT6geTjwFXg20+h9TBubhUYL0U/WFa4XT9k0DzLAjByRfPlSIfN/sjPSE4V/KGC87pCat3TwIQKFs4X9LR/6vRu0asQ4woS2tpfR5hrMTI0Rl/DYRp3Msze77W3IT9uHO8j4GWQbHWS2BmDJc4Xu9IHh8SO/qsdVKcINV3Cpycl5SU87uokI7ZGSetfddnMvRcfTs7mOce7RcXFEUgynkXkbimNrYPbENsQY5mdTCH/M0BlBmgQ6stXu9A7JTEOltdScCiTjs/r7a4C0oZS6AfFLNtO8/lqFw=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
