---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: licensetool
spec:
  encryptedData:
    .dockerconfigjson: AgA7IpW92l+k3ecsjyCNaJo+C8MLh+LNXElZrh/TcLkvsxtj520EnIOop6/8lPoorguariKviticEVhMcjYRdNNaL6AjBTJlqOgIUF2Ybtp4PmuN3sZY2ZeHliAY5M4jHRjIYnL/E49WbD1CVIeUn2R5EGqp7L/sJSDwB5nivXfu0zP+WZLtsGoUyUvBfrEhZ8CwD2/qa/okM9b4tA9hCV0WW2VcmsR8nQsf3L4K6QwQtMXoxvKvq2pDA2UV7p6ejO/+u3EfLRtXTY2OIlo1F/qtYTBTcM4gFQgSB5bmgMRnp1jtd5nXNM3GrMnmpzdo7pxDbXbJGFOL6wdGoT5Y4X2voW3fV54hWn7EadGwRCgszQC8oAGYP0kNWwXmCb9u+kjk87IpuSyrU/xRFzKZj1W7ArWBp5+FIxuANJRKnP37gU7Lz21IJeWdReE3brtF69uyoCnBdKjycQ8YIIPOe2X76b1vq4I+tKVidaiEl8W34/6VLhN6MwAxxnBtX9oBx967lMXCq3R0jxzwpQZtxKBXGJEyA0jR9KKgai4f47gjtE1vnkEanUrZpPCrkOjtj/Ln/Bfjgr8VjuH+sg78K1WLo4kLeghfBQTB7qf2CLeVqnumCDAEiUFiCCPLw3n0Ig7Df9f5UIrsqlvQF9xyWFQtTfxqnNUOcm42lON4Sa6vzWleG+/uy1oxjXCkdEigmLuSuGDTiaHZyudgRyPMAfMvYlOjr1tbBbXKOdS7bMceKyKFBfPRpmliA0mic8evh0Ar69Ckh/0a0zxlYEvuuGwgUx/xoeVKJ1mWMP8TVIG6KSWuZxoNrW55mqSgRtHOaeZgrjmApXPs+kfbP+CeVTcTUHZZNeXG4jhKiEu9kpxJiPdp014Y5Ak5ATzjG1pR4rL4NeMwGKZvcRmlBwQso1oddFm288hCwDTa7CvPOqCST0bsz/qGUNK2shJgUJRxll0=
  template:
    metadata:
      name: regcred
      namespace: licensetool
    type: kubernetes.io/dockerconfigjson
