apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: licensetool

resources:
  - ../base
  - ingress-nginx.yaml
  - secrets/regcred.sealedsecret.yaml
  - secrets/licensetool-env.sealedsecret.yaml
  - secrets/licensetool-profiles-auth.sealedsecret.yaml
  - secrets/licensetool-profiles-sharepoint.sealedsecret.yaml
  - secrets/licensetool-profiles-tenants.sealedsecret.yaml
  - secrets/licensetool-cert-infos.sealedsecret.yaml
  - secrets/licensetool-cert-iseschool.sealedsecret.yaml
  - secrets/licensetool-cert-iseschool2013.sealedsecret.yaml
  - secrets/licensetool-cert-flask-service-iseapp-1588.sealedsecret.yaml
  - secrets/licensetool-tls.sealedsecret.yaml

images:
  - name: docker.io/radballmigi/licensemonitor-dev
    newTag: latest

patches:
  - path: patches/deployment-patch.yaml
