volumeMounts:
  - name: profiles
    mountPath: /app/config-profiles
    readOnly: true
  - name: certs
    mountPath: /app/certs
    readOnly: true

volumes:
  - name: profiles
    secret:
      secretName: licensetool-profiles
  - name: certs
    secret:
      secretName: licensetool-certs
