apiVersion: v1
kind: Service
metadata:
  name: licensetool
  labels:
    app: licensetool
spec:
  selector:
    app: licensetool
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
