apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: licensetool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://github.com/Radball-Migi/HF-ITCNE24-SemArbeit4-LicenseMonitor-K8s"
    targetRevision: "main"
    path: infra/k8s/apps/licensetool/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: licensetool
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
    syncOptions:
      - CreateNamespace=true
