apiVersion: apps/v1
kind: Deployment
metadata:
  name: licensetool
  namespace: default
  labels:
    app: licensetool
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: licensetool
  template:
    metadata:
      labels:
        app: licensetool
    spec:
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: profiles-auth
          secret:
            secretName: licensetool-profiles-auth
        - name: profiles-sharepoint
          secret:
            secretName: licensetool-profiles-sharepoint
        # - name: certs
        #   secret:
        #     secretName: licensetool-certs
        - name: certs-infos
          secret:
            secretName: licensetool-cert-infos
        - name: licensetool-cert-iseschool
          secret:
            secretName: licensetool-cert-iseschool
        - name: licensetool-cert-iseschool2013
          secret:
            secretName: licensetool-cert-iseschool2013
        - name: licensetool-cert-flask-service-iseapp-1588
          secret:
            secretName: licensetool-cert-flask-service-iseapp-1588

      containers:
        - name: licensetool
          image: docker.io/radballmigi/licensemonitor-dev:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000

          envFrom:
            - secretRef:
                name: licensetool-env

          volumeMounts:
            - name: profiles-auth
              mountPath: /app/config-profiles/auth
              readOnly: true
            - name: profiles-sharepoint
              mountPath: /app/config-profiles/sharepoint
              readOnly: true
            # - name: certs
            #   mountPath: /app/certs
            #   readOnly: true
            - name: certs-infos
              mountPath: /app/certs/infos
              readOnly: true
            - name: licensetool-cert-iseschool
              mountPath: /app/certs/iseschool
              readOnly: true
            - name: licensetool-cert-iseschool2013
              mountPath: /app/certs/iseschool2013
              readOnly: true
            - name: licensetool-cert-flask-service-iseapp-1588
              mountPath: /app/certs/flask-service-iseapp-1588
              readOnly: true

