apiVersion: apps/v1
kind: Deployment
metadata:
  name: licensetool
  namespace: default
  labels:
    app: licensetool
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: licensetool
  template:
    metadata:
      labels:
        app: licensetool
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: licensetool
          image: docker.io/radballmigi/licensemonitor-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000