apiVersion: v1
kind: Service
metadata:
  name: licensetool
  namespace: prod
  labels:
    app: licensetool
spec:
  type: NodePort
  selector:
    app: licensetool
  ports:
    - name: http
      port: 80
      targetPort: http   # verweist auf containerPort:5000 (per Name)
      protocol: TCP
      nodePort: 30080