name: Syntax Tests

on:
  push:
    branches-ignore:  
      - main
      - dev

    paths:
      - 'ressources/licensetool/**'

jobs:
  tests:
    name: lint-test-security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            ${{ vars.WORKDIR }}/licensetool/requirements.txt
            ${{ vars.WORKDIR }}/licensetool/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ vars.WORKDIR }}/licensetool/requirements.txt
          pip install pytest flake8 black isort mypy bandit ruff

      - name: Lint with ruff
        working-directory: ${{ vars.WORKDIR }}/licensetool
        run: ruff check .

      # - name: Run Unit Tests
      #   run: |
      #     pytest ${{ vars.WORKDIR }}/licensetool/tests/. -v --tb=short

      # - name: Run Integration Tests
      #   run: |
      #     pytest ${{ vars.WORKDIR }}/licensetool/tests/integration/. -v --tb=short
      #     continue-on-error: false
          